### PR TITLE
docs: Update reactotron recipe

### LINKED ISSUE #757: How to add reactron
https://github.com/infinitered/reactotron/blob/master/docs/quick-start-react-native.md

### PR DESCRIPTION
**Pull request by jmyrland**
Based on the existing docs & [this SO post](https://stackoverflow.com/questions/72947271/how-to-use-reactotron-redux-with-easy-peasy).

closes #757

### CODE REVIEW

**Comment by jmyrland** [comment]
I've excluded the `window.requestIdleCallback = null;` which might be essential for it to work on iOS.

1. Should we include it in the recipe?
2. Should we try to find a solution for [this issue](https://github.com/ctrlplusb/easy-peasy/issues/599#issuecomment-781258630)

**Comment by ctrlplusb** [comment]
Awesome. Perhaps we can just add a comment stating the potential issues around iOS with a link to the corresponding issue/discussion?

**Comment by jmyrland** [comment]
> Awesome. Perhaps we can just add a comment stating the potential issues around iOS with a link to the corresponding issue/discussion?

Added the "solution" as part of the snippet, with a link back to the issue

**Review by ctrlplusb — APPROVED** [review]
LGTM :)

**Pull request merged**
