### PR TITLE
[WIP] V2 - Adds ability to dynamically modify store model

### LINKED ISSUE #29: Lazy reducers
Often when code splitting, it's necessary to lazily add reducers. I haven't used easy-peasy yet, so if there is an idiomatic way, a quick doc update would be great!

### PR DESCRIPTION
**Pull request by ctrlplusb**
Closes #29

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Got it working in principal, but have no idea how to represent this via the type system.

Needs a massive code cleanup still too. 😊

**Comment by cevr** [comment]
I see that the API only supports adding one model at a time. Is there something limiting adding multiple models in one object as is done in the root model?

**Comment by ctrlplusb** [comment]
Hey @cevr - no restriction per se, but felt that models would be added in such a manner - i.e. a model namespace to represent a specific branch of your application.

Do you have experience with this type of thing? If so I would love your feedback on why you think being able to merge multiples keys in a single action would be valuable. 👍

**Comment by psachs21** [comment]
@ctrlplusb I've dealt with the typing issue before, unfortunately, the only thing we do is accept the eventual FULL state interface as a type param even if the initial model doesn't satisfy. There is no way to statically know if a model has been loaded or not. This leads to potentially accessing models that don't exist yet, but I think that is just a limit of static typing.

**Comment by cevr** [comment]
> Hey @cevr - no restriction per se, but felt that models would be added in such a manner - i.e. a model namespace to represent a specific branch of your application.
> 
> Do you have experience with this type of thing? If so I would love your feedback on why you think being able to merge multiples keys in a single action would be valuable. 👍

Sorry, not that I have any experience myself. I was asking out of curiosity to learn more! 🙇

**Pull request merged**
