### PR TITLE
feat: Shallow equality option for useStoreState()

### PR DESCRIPTION
**Pull request by joelmoss**
Currently. useStoreState() performs a strict equality check (`oldState === newState`) on its state, which is great for most cases. But sometimes you need to work with more complex state and return something that will always fail a strict check.

This PR adds support for a shallow equality check as follows:

```javascript
const store = createStore({
  count: 1,
  firstName: null,
  lastName: null
});

// In your component
const { count, firstName } = useStoreState(
  state => ({
    count: state.count,
    firstName: state.firstName,
  }),
  { shallowEquality: true }, /* this is new, an is false by default */
);
```

In the above case, if either the `count` or `firstName` state vars change, the equality check with be true, and the component will re-render. And if any other state is changed; for example, the `lastName`, the equality check will be true, and the component will not re-render.

The `shallowEquality` option is false by default, thus maintaining existing functionality.

See #275

### CODE REVIEW

**Comment by joelmoss** [comment]
@ctrlplusb anything I can do to push this along?

**Comment by ctrlplusb** [comment]
Hi @joelmoss - shall endeavour to review this week. I have had a very busy past few weeks.

**Comment by joelmoss** [comment]
No worries bud. Thx

Joel Moss
Develop with Style
DevelopWithStyle.com
07791 503309

https://www.linkedin.com/in/joelkmoss/
https://github.com/joelmoss
https://twitter.com/joelmoss

**Comment by ctrlplusb** [comment]
@joelmoss I've had a look. Thanks so much for this. Will be an awesome addition.

I'd like to request that we change the API somewhat. Instead of the configuration object could we instead accept an equality function as the second argument to useStoreState. This would very much be in line with the Redux useSelector hook then.

We could include a default shallow equality fn that user's could leverage.

This provides a lot more flexibility going forward IMO.

**Comment by joelmoss** [comment]
ok, yeah I like that. Leave it with me.

**Comment by joelmoss** [comment]
By the way, I noticed that the `shallowequal` package is included, so we can use that as the officialy provided equality function.

However, I'm not seeing why that package is included and where it used.

**Comment by joelmoss** [comment]
Actually, no matter. The `shallowequal` package accepts a customizer which we don't and won't ever use.

**Comment by joelmoss** [comment]
done!

**Comment by ctrlplusb** [comment]
Amazing thanks!

**Comment by crissdev** [comment]
@joelmoss Thanks for this feature. If possible please squash your commits into one and update the docs/example found in this commit 1d29a67ed116c1e38fe4ff6cad406ded8e1094eb, since it no longer matches the final implementation. This might be very useful to @ctrlplusb if he decides to use that in the documentation.

**Comment by joelmoss** [comment]
Done!

**Comment by crissdev** [comment]
@joelmoss Cool. I think `index.d.ts` should also be updated to include the changes to `useStoreState` and the new `shallowEqual` function. Do you want to give that a try?

**Comment by joelmoss** [comment]
Not familiar with TS, but will give it a go

**Comment by ctrlplusb** [comment]
@joelmoss - if you aren't comfortable with doing the TS don't stress. Let me know and I will pick that up for ya.

**Comment by joelmoss** [comment]
Yeah, sorry. Not familiar enough with TS to give this time. So any help would be appreciated, thx

Joel Moss
Develop with Style
DevelopWithStyle.com
07791 503309

https://www.linkedin.com/in/joelkmoss/
https://github.com/joelmoss
https://twitter.com/joelmoss

**Comment by joelmoss** [comment]
@ctrlplusb Just had a thought about this PR in the context of computed properties; do they also have a strict equality check? If so, we should probably allow this new option with computed properties too.

**Pull request merged**
