### PR TITLE
Next (v2.4.0)

### PR DESCRIPTION
**Pull request by ctrlplusb**
This is a WIP, that is being released as an alpha. I am hoping to get early feedback and testing on this. Open to making changes to address bugs or friction with the API itself. Please use this PR to discuss.

The PR is published under the `next` tag. You can install it like so:

```
npm install easy-peasy@next
```

The [docs](https://github.com/ctrlplusb/easy-peasy/tree/next) are being kept up to date to reflect these API additions.

Todo:
 - [ ] New docs website (in progress, https://easy-peasy.now.sh/)
   - [ ] Typescript API
   - [ ] Full Store API docs (including #98, #133)
   - [ ] More examples
   - [ ] Best practices 
 - [x] Local/multiple stores #131 (See https://codesandbox.io/s/easy-peasy-local-container-store-prototype-209xd for some prototyping on this)
 - [x] Aliased version of hooks #182 
 - [X] New `selector` helper (deprecates `select`) #175 + #170

### Renamed / Aliased hooks

In order to address some confusion around the hooks we have renamed the hooks, but have aliased them so that this won't be a breaking changed.

`useStore` -> `useStoreState`

`useActions` -> `useStoreActions`

`useDispatch` -> `useStoreDispatch`

The docs have been updated. No behavioural changes.

### New `selector` helper

The new `selector` helper is intended to allow you to create state selectors, i.e. functions that take in state and then return derived new state. We have decided to incorporate this helper within the library, as we can ensure that performance optimisations such as memoization are automatically performed against your selectors. Your selectors will automatically manage cache invalidation when updates to related state occurs.

This helper takes all of my learnings from the current `select` and attempts to resolve the problems and limitations that I identified with it. Specifically:

- It was too easy to accidentally introduce performance issues with `select`
- You could not access global state from within a `select`

This helper deprecates the `select` API. Any use of `select` will output a warning message, advising migration to the new helper. When the next major release of `easy-peasy` happens we will then remove the deprecated `select` helper.

You can read the docs for the selector [here](https://github.com/ctrlplusb/easy-peasy/tree/next#selector).

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Moving a comment placed in #177 by @homura here:

> derived state looks good, but I think "runtime arguments" possibly make derived confused. See reduxjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

Yeah, personally I am not a fan of returning a function to handle runtime arguments. It doesn't feel as natural to me. I also considered alternatives, like splitting the argument selectors and runtime arguments:

```javascript
import { selector } from 'easy-peasy';

const store = createStore({
  todos: {
    items: {
      1: { id: 1, text: 'Win the lottery' ]
    },
    getById: selector(
      [(state) => state.items], 
      //  👇 argument selectors
      ([items], [id]) => items[id]
      //         👆runtime args
  },
});

store.getState().todos.getById(1);
// { id: 1, text: "Win the lottery" }
```

So you receive two arguments to your selector. The first argument being an array containing the result of any argument selectors, and the second being an array containing any runtime arguments.  This is slightly more verbose, but at least it makes the distinction far more clear.

Thoughts @homura?

**Comment by homura** [comment]
> Moving a comment placed in #177 by @homura here:
> 
> > derived state looks good, but I think "runtime arguments" possibly make derived confused. See reduxjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument
> 
> Yeah, personally I am not a fan of returning a function to handle runtime arguments. This was the recommended approach in the original `select` helper, but it doesn't feel as natural to me. I'd rather bake in the ability to handle runtime arguments.
> 
> I also considered alternatives, like splitting the argument selectors and runtime arguments:
> 
> ```js
> import { selector } from 'easy-peasy';
> 
> const store = createStore({
>   todos: {
>     items: {
>       1: { id: 1, text: 'Win the lottery' ]
>     },
>     getById: selector(
>       [(state) => state.items], 
>       //  👇 argument selectors
>       ([items], [id]) => items[id]
>       //         👆runtime args
>   },
> });
> 
> store.getState().todos.getById(1);
> // { id: 1, text: "Win the lottery" }
> ```
> 
> So you receive two arguments to your selector. The first argument being an array containing the result of any argument selectors, and the second being an array containing any runtime arguments. This is slightly more verbose, but at least it makes the distinction far more clear.
> 
> Thoughts @homura?

How about adding two new API `selector` and `derived`. The `selector` always return a memoized function that is able to handle runtime argument, and the `derived` always return derived state. A  helper does only one thing is better.

**Comment by ctrlplusb** [comment]
I love that idea @homura

**Comment by bentron2000** [comment]
Hi @ctrlplusb, 

I thought I'd try out the new `selector` helper but I'm getting an error:

> Uncaught TypeError: easy_peasy_1.selector is not a function

So I thought I'd try and implement your example code as per the docs. 
I get the error there too. Not sure if this is a bug or if I'm doing something wrong.

[Here is a codesandbox that shows the problem](https://codesandbox.io/embed/easypeasytypescriptnestedstateissues-r58t5).

Cheers
B

**Comment by ctrlplusb** [comment]
@bentron2000 

Thanks for trying to review. What version of easy peasy do you have installed?

**Comment by ctrlplusb** [comment]
Sorry, skimmed over your codesandbox. I may have published the wrong branch. I'll look into this later. 👍

**Comment by ctrlplusb** [comment]
Hey @bentron2000 

I am not sure what happened with the publish. I republish it as and it appears to be working now.

Your updated sandbox: https://codesandbox.io/s/easypeasyselectorissue-mjsrs

**Comment by bentron2000** [comment]
> @bentron2000
> 
> Thanks for trying to review. What version of easy peasy do you have installed?

@ctrlplusb 

`2.4.0.alpha.2` both on my local copy and in the codesandbox example.

**Comment by bentron2000** [comment]
> Hey @bentron2000
> 
> I am not sure what happened with the publish. I republish it as and it appears to be working now.
> 
> Your updated sandbox: https://codesandbox.io/s/easypeasyselectorissue-mjsrs

Thanks so much! I have it working locally as well.

In regards to types for the selectors - as you can see in the code sandbox, the `state` object passed into the `argumentResolvers` is currently showing as `any`. (stuff.ts line 14)
I assume this should be receiving the type defined above at line 6?

Also - should we expect `storeState ` passed into the `argumentResolvers` to automatically receive correct types from the model?

(hope this is useful - don't want to pepper you with queries that aren't)

Cheers
B

**Comment by ctrlplusb** [comment]
Hey @bentron2000 

Yeah I need to document how to use the Typescript types. See the definition tests as a reference though. You can get full typing on them still. 

https://github.com/ctrlplusb/easy-peasy/blob/next/src/__tests__/typescript/selector.ts

I definitely want to make some adjustments to this helpers API overall. But would really appreciate it if you could try it out and raise any issues you feel like you have with it.

**Comment by bentron2000** [comment]
> Hey @bentron2000
> 
> Yeah I need to document how to use the Typescript types. See the definition tests as a reference though. You can get full typing on them still.
> 
> https://github.com/ctrlplusb/easy-peasy/blob/next/src/__tests__/typescript/selector.ts
> 
> I definitely want to make some adjustments to this helpers API overall. But would really appreciate it if you could try it out and raise any issues you feel like you have with it.

Hi @ctrlplusb, 

I took a look and applied the types as per the example in the tests you showed me - however I am not sure the types are flowing through as expected. The `argumentResolvers` still show as implicit `any`
The `selector` function is correctly typed though :)

Below is an annotated codesandbox showing the issue

Cheers

B
[https://codesandbox.io/embed/easypeasyselectorissue-5jlgt](https://codesandbox.io/embed/easypeasyselectorissue-5jlgt)

**Comment by bentron2000** [comment]
Just a note on the above @ctrlplusb - this error only seems to happen in codesandbox - When I do the same in my local project,  it works as expected - state and globalState are typed properly.

**Comment by lishine** [comment]
addModel doesn't exist in next version currently
#180

**Comment by lishine** [comment]
Found it :)

**Comment by lishine** [comment]
But I see that model is added at key.
Will you make it more general - adding model at path?

**Pull request merged**
