### PR TITLE
Add Typescript typings

### LINKED ISSUE #21: Add TypeScript typings
I'm happy to do if you don't use TypeScript. I've begun a WIP, but have a way to go before it's in usable form. It may take me a bit of time to fit in around my other work....

### PR DESCRIPTION
**Pull request by christianchown**
Closes #21 

Adds the following types to define a Model for the store
- Effect<Model, _optional_ Payload, _optional_ ReturnType>
- Action<StoreValues, _optional_ Payload>
- Reducer\<State\>
- Select<StoreValues, ResultantType>

Adds the following types to extract useful shapes from a Model
- ModelValues\<Model\>
- MutableModelValues\<Model\>
   _store values that can be mutated by actions i.e. ones not from `select(...)`)_ or `reducer(...)`
- ModelActions\<Model\>

Adds the following types for use in `createStore`
- Config\<Model\>
- Store\<Model\>

Adds the following type for use in `useAction`
- Dispatch\<Model\>

And adds type information for the public API
- createStore\<Model\>
- effect\<Model, _optional_ Payload, _optional_ ReturnType\>
- reducer\<State\>
- select\<StoreValues, ResultantType\>
- StoreProvider\<Model\>
- useStore(mapState: ModelValues\<Model\> => StateValue)
- useAction(dispatch: Dispatch\<Model\> => ActionPayload)

The types in the public API are opt-in, and will default to `any` if no generics are provided.

```typescript
import React from 'react';
import {
  createStore,
  effect,
  reducer,
  select,
  useStore,
  useAction,
  Action,
  Effect,
  Reducer,
  Select,
  ModelValues,
  Dispatch,
} from 'easy-peasy';
import { Action as ReduxAction } from 'redux';
import todoService from './toDoService';

interface TodoValues {
  items: Array<string>;
}

interface TodoValuesAndSelectors extends TodoValues {
  lengthOfItems: number;
}

interface TodoActions {
  saveTodo: Effect<Model, string, Promise<number>>;
  todoSaved: Action<TodoValuesAndSelectors, string>;
  lengthOfItems: Select<TodoValuesAndSelectors, number>;
}

interface Model {
  todos: TodoValues & TodoActions;
  counter: Reducer<number>;
}

const store = createStore<Model>({
  todos: {
    items: [],

    saveTodo: effect(async (dispatch, payload, getState) => {
      const saved = await todoService.save(payload);
      dispatch.todos.todoSaved(saved); // 👍 correctly typed

      // dispatch.todos.todoSaved(1);
      // 👍 errors! (1 is not assignable to string)

      // dispatch.notToDos.something();
      // 👍 errors! (notToDos does not exist on Dispatch<Model>)

      const { lengthOfItems } = getState().todos; // 👍 correctly typed
      if (lengthOfItems > 10) {
        await todoService.reportBigUsage();
      }
      return lengthOfItems;
    }),

    todoSaved: (state, payload) => {
      state.items.push(payload); // 👍 correctly typed

      // state.items.push(1);
      // 👍 correctly errors! (1 is not assignable to string)

      if (state.lengthOfItems > 10) {
        // 👍 correctly typed
      }
    },

    lengthOfItems: select(state => {
      return state.items.length; // 👍 correctly typed
    }),
  },

  counter: reducer((state, action: ReduxAction) => {
    // 👍 correctly typed
    switch (action.type) {
      case 'INCREMENT':
        return state + 1;
      default:
        return state;
    }
  }),
});

function TodoComponent() {
  const num = useStore((state: ModelValues<Model>) => state.todos.lengthOfItems); // 👍 correct
  const save = useAction((dispatch: Dispatch<Model>) => dispatch.todos.saveTodo); // 👍 correct
  const counter = useStore((state: ModelValues<Model>) => state.counter); //         👍 correct

  // const num: number = useStore((state: ModelValues<Model>) => state.todos.items);
  // 👍 correctly errors - (string[] is not assignable to number)

  // const a: (payload: number) => void = useAction(
  //    (dispatch: Dispatch<Model>) => dispatch.todos.saveTodo
  //  );
  // 👍 correctly errors - (payload incompatible - number is not assignable to string)

  return (
    <>
      <p>
        There are {num} components and the counter is {counter}
      </p>
      <button
        type="button"
        onClick={() => {
          save('another');
        }}
      >
        Add another!
      </button>
    </>
  );
}
```
_Edit_: Added optional return type for Effect 
_Edit_: Changed shape of useStore
_Edit_: Added Dispatch and changed shape of useAction

### CODE REVIEW

**Comment by christianchown** [comment]
Caveat on usage with `react-redux`: https://github.com/ctrlplusb/easy-peasy/issues/21#issuecomment-440478417

**Comment by ctrlplusb** [comment]
Woot!

I am going to try and wrap my head around a Typescript setup this weekend hopefully. I've got experience with Flow so hopefully it should be too painful in getting started.

Excited to play with this. 👍

**Comment by ctrlplusb** [comment]
Update on this one - I have been learning TypeScript. 😎

Been enjoying the experience mostly, and soon I will be able to give this a proper review from the perspective of a TypeScript user. 👍

Apologies for the delay.

**Comment by skulptur** [comment]
What's the status on this?

**Comment by ctrlplusb** [comment]
FYI, after a brief play I don't see any issue with merging values and selectors. Modifying your example:

```typescript
interface TodoValues {
  items: Array<string>;
  lengthOfItems: number;
}

interface TodoActions {
  saveTodo: Effect<Model, string, Promise<number>>;
  todoSaved: Action<TodoValues, string>;
  lengthOfItems: Select<TodoValues, number>;
}

interface Model {
  todos: TodoValues & TodoActions;
  counter: Reducer<number>;
}
```

**Comment by ctrlplusb** [comment]
Been playing around a bit more. Great idea to add the `readonly` key to your selector attributes to avoid any unintentional mutations.

Also, it appears the dispatch doesn't have the model attached for me:

screenshot 2019-01-09 17 35 41

**Comment by skulptur** [comment]
Hey @christianchown, I am using your types and I just wanted to point out that I had to make a small modification to the EffectAction type. Basically I just added another parameter ```meta:any``` to support the generic helper pattern showcased in the readme.

```typescript
  type EffectAction<Model, Payload, EffectResult> = (
    dispatch: Dispatch<Model>,
    payload: Payload,
    getState: () => Readonly<ModelValues<Model>>,
    injections: any,
    meta: any // 👈
  ) => EffectResult
```

How can I contribute to the typings in case I find more stuff, shall I just mention it here?

cheers

**Comment by christianchown** [comment]
Hi @skulptur, yes either mention here, or (better yet) open a PR on my fork, https://github.com/christianchown/easy-peasy/tree/typescript-typings, although I'll make the meta changes when I get the chance

(also @ctrlplusb - can you try my alternative typings at https://github.com/christianchown/easy-peasy-typescript/blob/formula-wip/src/easy-peasy.d.ts and let me know if it still gives you errors?)

**Comment by ctrlplusb** [comment]
@christianchown - duuuuude. The level of work you have put into this. Insane man. Loads of love to you!

I've been trying to review the internals of it very deeply and I am starting to understand how complex this is. The recursive and self referencing nature of the model is very tricky to reconcile.

To better understand it all I have spun up a branch and am playing around with the types. It's been interesting to say the least, but I think I am starting to get my head around the compiler.

I'll ping you soon with my latest thoughts and possible additions. 👍

**Comment by ctrlplusb** [comment]
Hi @christianchown - I ended up diverging so much I've created an alternative set of types (#57).

Will be worthwhile analysing both and seeing what we can finalise with. 👍

**Comment by ctrlplusb** [comment]
Hey all, to help easily test these definitions I have published a tagged version of this pr. You can install it like so:

```
npm install easy-peasy@typescript-cc
```

Please give us feedback as I feel like with two PRs on the go we are starting to circle down to the final solution. 👍

**Comment by aalpgiray** [comment]
I got time to take a look at this but getting this same error again with. I am missing something clearly.

image

**Comment by ctrlplusb** [comment]
@aalpgiray have you tried #57?

I think we are going to move towards this PR. 👍

**Comment by ctrlplusb** [comment]
@christianchown - closing this for now so that we can focus on #57 ❤️

**Pull request closed without merging**
