### PR TITLE
feat. Pass debug trace options to dev tools

### PR DESCRIPTION
**Pull request by el-gringo**

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Hi @el-gringo 👋

Thanks for this. I think it's great to consider custom config for the underlying dev tools. 👍

I had a brief look at your implementation. Would you consider an adaptation to your API?

It would be great to have the `devTools` configuration value to be either a `boolean` or a configuration `object`.

i.e.

```javascript
createStore(model, {
  devTools: true
});

// or

createStore(model, {
  devTools: {
    tracing: true,
    traceLimit: 25
  }
});
```

What do you think?

**Comment by el-gringo** [comment]
Yes, this is a great idea !

**Comment by ctrlplusb** [comment]
@el-gringo are you still open to doing this :)

**Comment by el-gringo** [comment]
I've made the changes. There is something that can be confusing about the name option which can be in the `createStore` option and in the devTools object.
`
createStore(model, { name: 'test1', devTools: { name: 'test2' } })
`
test2 will be the store name

**Review by w3bdesign — APPROVED** [review]

**Comment by corysimmons** [comment]
Any chance of this getting revisited? Being able to trace would help eliminate a lot of my future _"What's going on with this thing?"_ questions. :3

**Review by w3bdesign — APPROVED** [review]

**Comment by jmyrland** [comment]
I was unable to update this branch with the latest changes from master.
I created #771 as a continuation of this work. Thanks for your efforts @el-gringo 👏

**Pull request closed without merging**
