### PR TITLE
Disable devTools by default if NODE_ENV === production

### PR DESCRIPTION
**Pull request by christianchown**
and fix the typo in the README

### CODE REVIEW

**Comment by christianchown** [comment]
Ah - just read https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67#d14d which I didn't know about...

**Comment by ctrlplusb** [comment]
Yeah, let's avoid any possible performance issues as it is very possible the process.env would be hit per request in an SSR environment. Fixing the property name definitely helps though!! 😊 

We could consider more docs around this to educate adopters and allow them to choose a performance strategy that suits them. 👍

**Comment by christianchown** [comment]
Hi - the README now notes incorrectly that `devTools` default is true `if NODE_ENV !== 'production'` rather than `true`

**Comment by ctrlplusb** [comment]
Woops. I'll fix. Ta

**Pull request merged**
