### PR TITLE
V3

### PR DESCRIPTION
**Pull request by ctrlplusb**
**Note**

If you are upgrading from `easy-peasy@3.0.0-rc.0` to `easy-peasy@3.0.0-rc.6` please review the API and TypeScript docs relating to `actionOn`, `thunkOn`, and `computed`. In order to optimise the TypeScript DX I have made some breaking changes. Apologies for the break at RC phase, however, I hope you will agree it is worth it.  As things stand I am very happy with where we are at. I will let `easy-peasy@3.0.0-rc.6` sit for a short while and then will look to cut `easy-peasy@3.0.0`. Any early adopters and feedback will be super appreciated. 👍

---

[Updated website](https://easy-peasy-v3.now.sh/)

```
npm install easy-peasy@3.0.0-rc.6
```

v3 is considered the realisation of the "final" Easy Peasy API - taking all the evolution and learning from v2 to produce a long term stable API that we will commit to supporting and will do our best to avoid breaking changes moving forward.

**Todo**

- [x] Complete documentation on testing
- [x] Apply performance optimisations unlocked by removing deprecated APIs
- [x] Triple parse the website docs
- [x] Code cleanup triple parse
- [x] Ensure 100% code coverage

### Hot reloading support

Hot reloading is supported via the `store.reconfigure(model)` API. See #168 

### New [actionOn](https://easy-peasy-v3.now.sh/docs/api/action-on) and [thunkOn](https://easy-peasy-v3.now.sh/docs/api/thunk-on) APIs

These are the new and _only_ APIs by which to define action/thunk listeners with.

The [v3 website](https://easy-peasy-v3.now.sh/) has been updated with tutorials and API docs introducing these APIs.

We are _really_ sorry about the churn around listener APIs! This API was driven by community feedback so feeling far better about it. 👍

### Removed deprecated APIs

- `listen` (use the new [actionOn](https://easy-peasy-v3.now.sh/docs/api/action-on) or [thunkOn](https://easy-peasy-v3.now.sh/docs/api/thunk-on) APIs instead)
- `action` and `thunk` can no longer be configured as listeners (use the new [actionOn](https://easy-peasy-v3.now.sh/docs/api/action-on) or [thunkOn](https://easy-peasy-v3.now.sh/docs/api/thunk-on) APIs instead)
- `select` (use [computed](https://easy-peasy-v3.now.sh/docs/api/computed) instead)
- `selector` (use [computed](https://easy-peasy-v3.now.sh/docs/api/computed) instead)
- `useStore` (renamed to [useStoreState](https://easy-peasy-v3.now.sh/docs/api/use-store-state))
- `useActions` (renamed to [useStoreActions](https://easy-peasy-v3.now.sh/docs/api/use-store-actions))
- `useDispatch` (renamed to [useStoreDispatch](https://easy-peasy-v3.now.sh/docs/api/use-store-dispatch))
- store instances have had the following properties removed:
  - `triggerListener`
  - `triggerListeners`
  - `useStoreState` (import from 'easy-peasy' or use [createTypedHooks](https://easy-peasy-v3.now.sh/docs/api/create-typed-hooks) for TS)
  - `useStoreActions` (import from 'easy-peasy' or use [createTypedHooks](https://easy-peasy-v3.now.sh/docs/api/create-typed-hooks) for TS)
  - `useStoreDispatch` (import from 'easy-peasy' or use [createTypedHooks](https://easy-peasy-v3.now.sh/docs/api/create-typed-hooks) for TS)

### Thunks can be either asynchronous and synchronous 

Using `async/await` or returning a `Promise` from a thunk will maintain its previous async behaviour.

However, if you do neither of the above your thunk will be executed synchronously. Therefore you would get eager updates to your state. This can be handy for encapsulating log based action dispatching within a think.

```javascript
addProduct: thunk((actions, payload) => {
  switch (payload.type) {
    case 'SHOES': 
		actions.addShoe(payload);
        break;
    case 'VEGETABLE':
        // ...
  }
});
```

### Returning immutable state from actions

If you prefer to return new immutable state from your actions, rather than mutating the state, you need to set the new `disableImmer` flag.

```javascript
import { createStore, action } from 'easy-peasy';

const model = {
  todos: [],
  addTodo: action((state, payload) => {
    // 👇 new immutable state returned
    return [...state, payload];
  })
}

const store = createStore(model, {
  disableImmer: true // 👈 set the flag
})
```

Failing to disable immer may result in strange errors if you are using computed properties.

### computed

In order to optimise the Typescript experience we have made a fairly small change to the computed API. If you wish to use state resolvers, these now need to be defined as the first argument.

_Before_

```javascript
const basketModel = {
  productIds: [],
  products: computed(
    (productIds, products) => productIds.map(id => products[id]),
    [
      state => state.productIds,
      (state, storeState) => storeState.products.items
    ]
  )
};
```

_After_

```javascript
const basketModel = {
  productIds: [],
  products: computed(
    [
      state => state.productIds,
      (state, storeState) => storeState.products.items
    ],
    (productIds, products) => productIds.map(id => products[id])
  )
};
```

Computed properties not using state resolvers remain unchanged.

### useStoreState API update

[useStoreState](https://easy-peasy-v3.now.sh/docs/api/use-store-state)` (previously `useStore`) no longer needs/accepts the dependencies 2nd argument. Your state will get mapped correctly if they use external values, like props, within the `mapState` function.

### Typescript

We now requires >= `typescript@3.5.1` if you use the Typescript definitions. We recommend using the latest version, `typescript@3.5.3` at the time of writing, in order to ensure you are up to date with the latest bug fixes.

Create React App users can just install `typescript@3.5.3` as a dev dependency and the CRA build system will use that version. 👍

> Note: using a lower version of TypeScript _may_ still work, however, we will not be officially supporting them. Moving forward we will provide support for >= `typescript@3.5.x`

#### Computed

The `Computed` type no longer requires you to define the types for state resolvers. These will automatically be inferred.

_Before_

```typescript
interface BasketModel {
  productIds: string[];
  products: Computed<
    BasketModel, 
    Product[], 
    ResolvedState2<string[], Product[]>, 
    StoreModel
   >
}
```

_After_

```typescript
interface BasketModel {
  productIds: string[];
  products: Computed<
    BasketModel, 
    Product[],
    StoreModel
   >
}
```

### CODE REVIEW

**Comment by BjoernRave** [comment]
wow, that diff, so sexy

**Comment by ctrlplusb** [comment]
Soooooo satisfying.

**Comment by waynevanson** [comment]
> * `createTypedHooks` (use the typed hooks bound to store instead)
> * `useStore` (renamed to `useStoreState`)
> * `useActions` (renamed to `useStoreActions`)
> * `useDispatch` (renamed to `useStoreDispatch`)

Loving the convention and consistency!

**Comment by jmyrland** [comment]
Hi @ctrlplusb ! **This is looking real good** 👏 

Because we have a pretty well testet system with easy-peasy integrated, I figured I would install the new version to check it out!

Quick feedback: I would recommend moving the section about `createTypedHooks` on the typescript docs to the top. Got stuck on exporting `useStoreState<StoreModel>` until I scrolled down on the docs page. Note to self; read the full page before getting into the code 🤦‍♂

Loving the new [listener API](https://easy-peasy-v3.now.sh/docs/typescript-tutorial/adding-typed-listeners.html)! For listeners against multiple actions - I assume returning an array from the "target resolver" is the way to go. If that is the case - a quick note in the docs would be great:
> The action resolver might return an array of actions - if you want the listener to fire for multiple actions/thunks 👍 

I'll continue my journey of upgrading & testing the new version. If I stumble upon something strange - I'll be sure to let you know!

High-fives & well done to all the involved! 👏 🎉 🎊

**Pull request merged**
